package src;

import com.sun.net.httpserver.*;
import java.io.*;
import java.net.InetSocketAddress;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Server.java — HTTP server + request routing + cart/bookings logic.
 * All HTML output is generated by UI.java (pure Java) — no template files.
 */
public class Server {
    private static final int PORT = Integer.parseInt(System.getenv().getOrDefault("PORT", "8080"));
    private static final ProductService productService = new ProductService();
    private static final Map<String, Cart> sessions = new ConcurrentHashMap<>();
    private static final Map<String, String> sessionToUser = new ConcurrentHashMap<>();
    private static final Set<String> adminSessions = ConcurrentHashMap.newKeySet();
    private static final String ADMIN_USER = "admin";
    private static final String ADMIN_PASS = "admin123";
    private static final List<Booking> orders = Collections.synchronizedList(new ArrayList<>());
    private static final List<User> users = Collections.synchronizedList(new ArrayList<>());
    private static final String DATA_DIR = System.getenv().getOrDefault("DATA_DIR", ".");
    private static final String ORDERS_FILE = DATA_DIR + File.separator + "orders.json";
    private static final String USERS_FILE = DATA_DIR + File.separator + "users.json";

    public static void main(String[] args) throws Exception {
        loadOrders();
        loadUsers();
        HttpServer server = HttpServer.create(new InetSocketAddress(PORT), 0);
        server.createContext("/", Server::handleRequest);
        server.setExecutor(null);
        server.start();
        System.out.println("========================================");
        System.out.println("   MEGA-KART 3D E-Commerce Server");
        System.out.println("   Running on http://localhost:" + PORT);
        System.out.println("   All pages generated by Java (UI.java)");
        System.out.println("========================================");
    }

    private static void handleRequest(HttpExchange exchange) throws IOException {
        String path = exchange.getRequestURI().getPath();
        String query = exchange.getRequestURI().getQuery();
        String sessionId = getSessionId(exchange);
        Map<String, String> params = parseQuery(query);

        try {
            if (path.equals("/")) {
                send(exchange, 200, UI.intro(), "text/html");
            } else if (path.equals("/css/style.css")) {
                send(exchange, 200, UI.CSS, "text/css");
            } else if (path.equals("/js/app.js")) {
                send(exchange, 200, UI.JS, "application/javascript");
            } else if (path.equals("/js/intro.js")) {
                send(exchange, 200, UI.INTRO_JS, "application/javascript");
            } else if (path.equals("/shop")) {
                handleShop(exchange, params);
            } else if (path.equals("/shop/")) {
                sendRedirect(exchange, "/shop");
            } else if (path.startsWith("/product/")) {
                Long id = parseLongSafe(path.substring("/product/".length()));
                if (id == null) { send(exchange, 404, UI.notFound(), "text/html"); return; }
                handleProductDetail(exchange, id);
            } else if (path.equals("/cart")) {
                handleCartPage(exchange, sessionId);
            } else if (path.startsWith("/cart/add/")) {
                Long id = parseLongSafe(path.substring("/cart/add/".length()));
                if (id == null) { sendRedirect(exchange, "/shop"); return; }
                Product p = productService.getById(id);
                if (p == null) { sendRedirect(exchange, "/shop"); return; }
                Cart cart = sessions.computeIfAbsent(sessionId, k -> new Cart());
                cart.addItem(p);
                sendRedirect(exchange, params.getOrDefault("from", "/shop"));
            } else if (path.startsWith("/cart/remove/")) {
                Long id = parseLongSafe(path.substring("/cart/remove/".length()));
                if (id != null) {
                    sessions.computeIfAbsent(sessionId, k -> new Cart()).removeItem(id);
                }
                sendRedirect(exchange, "/cart");
            } else if (path.equals("/cart/update")) {
                Long pid = parseLongSafe(params.getOrDefault("productId", "0"));
                int qty = parseIntSafe(params.getOrDefault("quantity", "1"), 1);
                if (pid != null) {
                    sessions.computeIfAbsent(sessionId, k -> new Cart()).updateQuantity(pid, qty);
                }
                sendRedirect(exchange, "/cart");
            } else if (path.equals("/cart/clear")) {
                sessions.computeIfAbsent(sessionId, k -> new Cart()).clear();
                sendRedirect(exchange, "/cart");
            } else if (path.equals("/checkout")) {
                handleCheckout(exchange, sessionId);
            } else if (path.equals("/checkout-success")) {
                handleCheckoutSuccess(exchange);
            } else if (path.equals("/login")) {
                handleLogin(exchange, sessionId);
            } else if (path.equals("/register")) {
                handleRegister(exchange, sessionId);
            } else if (path.equals("/logout")) {
                sessionToUser.remove(sessionId);
                sendRedirect(exchange, "/");
            } else if (path.equals("/admin/login")) {
                handleAdminLogin(exchange, sessionId);
            } else if (path.equals("/admin/logout")) {
                adminSessions.remove(sessionId);
                sendRedirect(exchange, "/admin/login");
            } else if (path.equals("/admin")) {
                handleAdmin(exchange, sessionId);
            } else if (path.startsWith("/admin/remove/")) {
                removeOrder(URLDecoder.decode(path.substring("/admin/remove/".length()), StandardCharsets.UTF_8));
                sendRedirect(exchange, "/admin");
            } else {
                send(exchange, 404, UI.notFound(), "text/html");
            }
        } catch (Exception e) {
            e.printStackTrace();
            send(exchange, 500, "<h1>500 Internal Server Error</h1><p>" + UI.esc(e.getMessage()) + "</p>", "text/html");
        }
    }

    private static void handleShop(HttpExchange exchange, Map<String, String> params) throws IOException {
        String search = params.get("search");
        String category = params.get("category");
        List<Product> products = productService.getBySearchOrCategory(search, category);
        String title;
        if (search != null && !search.trim().isEmpty()) {
            title = "Search: \"" + UI.esc(search) + "\"";
        } else if (category != null && !category.isEmpty()) {
            title = UI.cap(category) + " Products";
        } else {
            title = "All Products";
        }
        send(exchange, 200, UI.shop(title, products, category, getCart(exchange).getItemCount(), productService.getDeals(), currentUsername(exchange)), "text/html");
    }

    private static void handleProductDetail(HttpExchange exchange, long id) throws IOException {
        Product p = productService.getById(id);
        if (p == null) { sendRedirect(exchange, "/shop"); return; }
        send(exchange, 200, UI.product(p, getCart(exchange).getItemCount(), currentUsername(exchange)), "text/html");
    }

    private static void handleCartPage(HttpExchange exchange, String sessionId) throws IOException {
        Cart cart = sessions.getOrDefault(sessionId, new Cart());
        send(exchange, 200, UI.cart(cart, cart.getItemCount(), currentUsername(exchange)), "text/html");
    }

    private static void handleCheckout(HttpExchange exchange, String sessionId) throws IOException {
        if (exchange.getRequestMethod().equalsIgnoreCase("GET")) {
            Cart cart = sessions.getOrDefault(sessionId, new Cart());
            if (cart.getItems().isEmpty()) { sendRedirect(exchange, "/cart"); return; }
            send(exchange, 200, UI.checkout(cart, cart.getItemCount(), currentUsername(exchange)), "text/html");
            return;
        }
        String body = new String(exchange.getRequestBody().readAllBytes(), StandardCharsets.UTF_8);
        Map<String, String> form = parseForm(body);
        Cart cart = sessions.getOrDefault(sessionId, new Cart());
        if (cart.getItems().isEmpty()) { sendRedirect(exchange, "/cart"); return; }
        String orderId = "MK" + System.currentTimeMillis();
        Booking b = new Booking(orderId,
            empty(form.get("name"), "Customer"), form.getOrDefault("email", ""),
            form.getOrDefault("address", ""), form.getOrDefault("phone", ""),
            new ArrayList<>(cart.getItems()), cart.getTotal(), cart.getTotal() * 0.08, cart.getTotal() * 1.08);
        orders.add(b);
        saveOrders();
        cart.clear();
        sessions.put(sessionId, cart);
        sendRedirect(exchange, "/checkout-success?order=" + orderId);
    }

    private static void handleCheckoutSuccess(HttpExchange exchange) throws IOException {
        String orderId = "";
        String q = exchange.getRequestURI().getRawQuery();
        if (q != null) {
            for (String pair : q.split("&")) {
                String[] kv = pair.split("=", 2);
                if (kv.length == 2 && kv[0].equals("order")) orderId = URLDecoder.decode(kv[1], StandardCharsets.UTF_8);
            }
        }
        send(exchange, 200, UI.success(orderId, currentUsername(exchange)), "text/html");
    }

    private static void handleAdmin(HttpExchange exchange, String sessionId) throws IOException {
        if (!adminSessions.contains(sessionId)) {
            sendRedirect(exchange, "/admin/login");
            return;
        }
        double revenue = orders.stream().mapToDouble(Booking::getTotal).sum();
        send(exchange, 200, UI.admin(orders, UI.inr(revenue), "admin"), "text/html");
    }

    private static void handleAdminLogin(HttpExchange exchange, String sessionId) throws IOException {
        if (exchange.getRequestMethod().equalsIgnoreCase("GET")) {
            if (adminSessions.contains(sessionId)) { sendRedirect(exchange, "/admin"); return; }
            send(exchange, 200, UI.adminLogin(null), "text/html");
            return;
        }
        String body = new String(exchange.getRequestBody().readAllBytes(), StandardCharsets.UTF_8);
        Map<String, String> form = parseForm(body);
        String user = form.getOrDefault("username", "");
        String pass = form.getOrDefault("password", "");
        if (user.equals(ADMIN_USER) && pass.equals(ADMIN_PASS)) {
            adminSessions.add(sessionId);
            sendRedirect(exchange, "/admin");
        } else {
            send(exchange, 200, UI.adminLogin("Invalid admin credentials. Please try again."), "text/html");
        }
    }

    // ============ AUTHENTICATION ============
    private static void handleLogin(HttpExchange exchange, String sessionId) throws IOException {
        if (exchange.getRequestMethod().equalsIgnoreCase("GET")) {
            String username = sessionToUser.get(sessionId);
            if (username != null) { sendRedirect(exchange, "/"); return; }
            send(exchange, 200, UI.login(null), "text/html");
            return;
        }
        String body = new String(exchange.getRequestBody().readAllBytes(), StandardCharsets.UTF_8);
        Map<String, String> form = parseForm(body);
        String username = empty(form.get("username"), "");
        String password = form.getOrDefault("password", "");
        User u = findUserByUsername(username);
        String error;
        if (u != null && u.getPassword().equals(password)) {
            sessionToUser.put(sessionId, username);
            sendRedirect(exchange, "/");
            return;
        }
        error = "Invalid username or password.";
        send(exchange, 200, UI.login(error), "text/html");
    }

    private static void handleRegister(HttpExchange exchange, String sessionId) throws IOException {
        if (exchange.getRequestMethod().equalsIgnoreCase("GET")) {
            String username = sessionToUser.get(sessionId);
            if (username != null) { sendRedirect(exchange, "/"); return; }
            send(exchange, 200, UI.register(null), "text/html");
            return;
        }
        String body = new String(exchange.getRequestBody().readAllBytes(), StandardCharsets.UTF_8);
        Map<String, String> form = parseForm(body);
        String username = form.getOrDefault("username", "").trim();
        String email = form.getOrDefault("email", "").trim();
        String password = form.getOrDefault("password", "");
        String error = null;
        if (username.isEmpty() || email.isEmpty() || password.isEmpty()) {
            error = "All fields are required.";
        } else if (findUserByUsername(username) != null || findUserByEmail(email) != null) {
            error = "Username or email already registered.";
        }
        if (error != null) {
            send(exchange, 200, UI.register(error), "text/html");
            return;
        }
        boolean isAdmin = username.equalsIgnoreCase("admin") || username.equalsIgnoreCase("megaowner");
        users.add(new User(username, email, password, isAdmin));
        saveUsers();
        sessionToUser.put(sessionId, username);
        sendRedirect(exchange, "/");
    }

    private static User findUserByUsername(String username) {
        if (username == null) return null;
        for (User u : users) if (u.getUsername().equalsIgnoreCase(username)) return u;
        return null;
    }

    private static User findUserByEmail(String email) {
        if (email == null) return null;
        for (User u : users) if (u.getEmail() != null && u.getEmail().equalsIgnoreCase(email)) return u;
        return null;
    }

    private static String currentUsername(HttpExchange exchange) {
        return sessionToUser.get(getSessionId(exchange));
    }

    private static void removeOrder(String orderId) {
        if (orderId == null || orderId.isEmpty()) return;
        orders.removeIf(b -> b.getOrderId() != null && b.getOrderId().equals(orderId));
        saveOrders();
    }

    // ============ PERSISTENCE (JSON file) ============
    private static void saveOrders() {
        synchronized (saveLock) {
            try (BufferedWriter w = Files.newBufferedWriter(Paths.get(ORDERS_FILE), StandardCharsets.UTF_8)) {
                StringBuilder sb = new StringBuilder("[");
                for (int i = 0; i < orders.size(); i++) {
                    if (i > 0) sb.append(",");
                    sb.append(toJson(orders.get(i)));
                }
                sb.append("]");
                w.write(sb.toString());
            } catch (IOException e) {
                System.err.println("Failed to save orders: " + e.getMessage());
            }
        }
    }

    private static String toJson(Booking b) {
        StringBuilder items = new StringBuilder("[");
        for (int i = 0; i < b.getItems().size(); i++) {
            CartItem ci = b.getItems().get(i);
            if (i > 0) items.append(",");
            items.append("{\"id\":").append(ci.getProduct().getId())
                 .append(",\"name\":\"").append(esc(ci.getProduct().getName())).append("\"")
                 .append(",\"quantity\":").append(ci.getQuantity())
                 .append(",\"price\":").append(ci.getProduct().getPrice()).append("}");
        }
        items.append("]");
        return "{\"orderId\":\"" + esc(b.getOrderId()) + "\",\"customerName\":\"" + esc(b.getCustomerName())
             + "\",\"customerEmail\":\"" + esc(b.getCustomerEmail()) + "\",\"phone\":\"" + esc(b.getPhone())
             + "\",\"address\":\"" + esc(b.getAddress()) + "\",\"subtotal\":" + b.getSubtotal()
             + ",\"gst\":" + b.getGst() + ",\"total\":" + b.getTotal()
             + ",\"timestamp\":" + b.getTimestamp() + ",\"items\":" + items + "}";
    }

    private static String esc(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static void loadOrders() {
        Path p = Paths.get(ORDERS_FILE);
        if (!Files.exists(p)) return;
        try {
            String content = Files.readString(p, StandardCharsets.UTF_8).trim();
            if (content.isEmpty() || content.equals("[]")) return;
            for (String chunk : extractJsonObjects(content)) {
                try {
                    String orderId = jsonGet(chunk, "orderId");
                    String name = jsonGet(chunk, "customerName");
                    String email = jsonGet(chunk, "customerEmail");
                    String phone = jsonGet(chunk, "phone");
                    String address = jsonGet(chunk, "address");
                    double subtotal = jsonGetNum(chunk, "subtotal");
                    double gst = jsonGetNum(chunk, "gst");
                    double total = jsonGetNum(chunk, "total");
                    long ts = (long) jsonGetNum(chunk, "timestamp");
                    List<CartItem> items = jsonGetItems(chunk);
                    Booking b = new Booking(orderId, name, email, address, phone, items, subtotal, gst, total);
                    b.setTimestamp(ts);
                    orders.add(b);
                } catch (Exception ignored) {}
            }
        } catch (IOException e) {
            System.err.println("Failed to load orders: " + e.getMessage());
        }
    }

    private static String jsonGet(String chunk, String key) {
        String needle = "\"" + key + "\":\"";
        int s = chunk.indexOf(needle);
        if (s < 0) return "";
        s += needle.length();
        int e = chunk.indexOf('"', s);
        return chunk.substring(s, Math.max(s, e));
    }

    private static double jsonGetNum(String chunk, String key) {
        String needle = "\"" + key + "\":";
        int s = chunk.indexOf(needle);
        if (s < 0) return 0;
        s += needle.length();
        int e = chunk.indexOf(',', s);
        int e2 = chunk.indexOf('}', s);
        int end = e2; if (e > 0 && e < end) end = e;
        try { return Double.parseDouble(chunk.substring(s, end).trim()); }
        catch (Exception x) { return 0; }
    }

    private static List<CartItem> jsonGetItems(String chunk) {
        List<CartItem> items = new ArrayList<>();
        String needle = "\"items\":[";
        int s = chunk.indexOf(needle);
        if (s < 0) return items;
        s += needle.length();
        int e = chunk.indexOf(']', s);
        if (e < 0) return items;
        String arr = chunk.substring(s, e);
        for (String obj : extractJsonObjects("[" + arr + "]")) {
            try {
                long id = (long) jsonGetNum(obj, "id");
                int qty = (int) jsonGetNum(obj, "quantity");
                Product p = productService.getById(id);
                if (p == null) continue;
                items.add(new CartItem(p, Math.max(1, qty)));
            } catch (Exception ignored) {}
        }
        return items;
    }

    private static String empty(String s, String d) {
        return (s == null || s.trim().isEmpty()) ? d : s;
    }

    // ============ USER PERSISTENCE (JSON file) ============
    private static void saveUsers() {
        synchronized (saveLock) {
            try (BufferedWriter w = Files.newBufferedWriter(Paths.get(USERS_FILE), StandardCharsets.UTF_8)) {
                StringBuilder sb = new StringBuilder("[");
                for (int i = 0; i < users.size(); i++) {
                    if (i > 0) sb.append(",");
                    User u = users.get(i);
                    sb.append("{\"username\":\"").append(esc(u.getUsername()))
                      .append("\",\"email\":\"").append(esc(u.getEmail()))
                      .append("\",\"password\":\"").append(esc(u.getPassword()))
                      .append("\",\"admin\":").append(u.isAdmin()).append("}");
                }
                sb.append("]");
                w.write(sb.toString());
            } catch (IOException e) {
                System.err.println("Failed to save users: " + e.getMessage());
            }
        }
    }

    private static void loadUsers() {
        Path p = Paths.get(USERS_FILE);
        if (!Files.exists(p)) return;
        try {
            String content = Files.readString(p, StandardCharsets.UTF_8).trim();
            if (content.isEmpty() || content.equals("[]")) return;
            for (String chunk : extractJsonObjects(content)) {
                try {
                    String username = jsonGet(chunk, "username");
                    String email = jsonGet(chunk, "email");
                    String password = jsonGet(chunk, "password");
                    boolean admin = jsonGetNum(chunk, "admin") >= 1;
                    users.add(new User(username, email, password, admin));
                } catch (Exception ignored) {}
            }
        } catch (IOException e) {
            System.err.println("Failed to load users: " + e.getMessage());
        }
    }

    private static Long parseLongSafe(String s) {
        if (s == null || s.trim().isEmpty()) return null;
        try { return Long.parseLong(s.trim()); }
        catch (NumberFormatException e) { return null; }
    }

    private static int parseIntSafe(String s, int def) {
        if (s == null || s.trim().isEmpty()) return def;
        try { return Integer.parseInt(s.trim()); }
        catch (NumberFormatException e) { return def; }
    }

    private static final Object saveLock = new Object();

    private static List<String> extractJsonObjects(String jsonArray) {
        List<String> objects = new ArrayList<>();
        int depth = 0;
        int start = -1;
        boolean inString = false;
        boolean escaped = false;
        for (int i = 0; i < jsonArray.length(); i++) {
            char c = jsonArray.charAt(i);
            if (escaped) { escaped = false; continue; }
            if (c == '\\' && inString) { escaped = true; continue; }
            if (c == '"') { inString = !inString; continue; }
            if (inString) continue;
            if (c == '{') {
                if (depth == 0) start = i;
                depth++;
            } else if (c == '}') {
                depth--;
                if (depth == 0 && start >= 0) {
                    objects.add(jsonArray.substring(start, i + 1));
                    start = -1;
                }
            }
        }
        return objects;
    }

    // ============ HTTP helpers ============
    private static Cart getCart(HttpExchange exchange) {
        return sessions.computeIfAbsent(getSessionId(exchange), k -> new Cart());
    }

    private static String getSessionId(HttpExchange exchange) {
        Object cached = exchange.getAttribute("sessionId");
        if (cached != null) return (String) cached;
        String cookie = exchange.getRequestHeaders().getFirst("Cookie");
        String id;
        if (cookie != null && cookie.contains("sessionId=")) {
            id = cookie.split("sessionId=")[1].split(";")[0].trim();
        } else {
            id = UUID.randomUUID().toString();
        }
        exchange.setAttribute("sessionId", id);
        return id;
    }

    private static void send(HttpExchange exchange, int code, String body, String contentType) throws IOException {
        byte[] bytes = body.getBytes(StandardCharsets.UTF_8);
        Headers h = exchange.getResponseHeaders();
        h.set("Content-Type", contentType + "; charset=UTF-8");
        h.set("Set-Cookie", "sessionId=" + getSessionId(exchange) + "; Path=/; Max-Age=3600");
        exchange.sendResponseHeaders(code, bytes.length);
        try (OutputStream os = exchange.getResponseBody()) { os.write(bytes); }
    }

    private static void sendRedirect(HttpExchange exchange, String location) throws IOException {
        exchange.getResponseHeaders().set("Location", location);
        exchange.getResponseHeaders().set("Set-Cookie", "sessionId=" + getSessionId(exchange) + "; Path=/; Max-Age=3600");
        exchange.sendResponseHeaders(302, -1);
        exchange.close();
    }

    private static Map<String, String> parseQuery(String query) {
        Map<String, String> params = new HashMap<>();
        if (query == null) return params;
        for (String pair : query.split("&")) {
            String[] kv = pair.split("=", 2);
            if (kv.length == 2) {
                params.put(URLDecoder.decode(kv[0], StandardCharsets.UTF_8),
                           URLDecoder.decode(kv[1], StandardCharsets.UTF_8));
            }
        }
        return params;
    }

    private static Map<String, String> parseForm(String body) {
        Map<String, String> params = new HashMap<>();
        if (body == null || body.isEmpty()) return params;
        for (String pair : body.split("&")) {
            String[] kv = pair.split("=", 2);
            if (kv.length == 2) {
                params.put(URLDecoder.decode(kv[0].replace("+", " "), StandardCharsets.UTF_8),
                           URLDecoder.decode(kv[1].replace("+", " "), StandardCharsets.UTF_8));
            }
        }
        return params;
    }
}
